### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by ThirteenAG** [cursey/kananlib#4]
Apologies for not sending a PR, I'll list a few minor things here:

https://github.com/cursey/kananlib/blob/main/src/Emulation.cpp

Maybe worth updating to latest bddisasm? I would require changing `#include <disasmtypes.h>` to `#include <bddisasm_types.h>`.
Also 
`ctx->Registers` -> `ctx->Arch.X86.Registers`
`ctx->Segments` -> `ctx->Arch.X86.Segments`
`ctx->Mode` -> `ctx->Arch.X86.Mode`
`ctx->Ring` -> `ctx->Arch.X86.Ring`

https://github.com/cursey/kananlib/blob/main/src/Module.cpp

`#pragma comment (lib, "shlwapi.lib")` is missing, required for PathRemoveFileSpecW.

https://github.com/cursey/kananlib/blob/main/src/Module.cpp
https://github.com/cursey/kananlib/blob/main/src/Scan.cpp

`GetModuleHandle` should be switched to `GetModuleHandleA`, since it only uses `std::string`. In unicode project it doesn't compile.

**Comment by praydog** [comment]
In my UEVR project which makes extensive use of bddisasm's bdshemu, I've found that updating it to latest breaks some of its scanning/automation tasks. Will need to spend some time on that to figure out what is wrong

**Comment by ThirteenAG** [comment]
I see, would be good to specify/include which version is recommended for now.
Upd: Just saw it inside .toml, nevermind then.
