### ISSUE TITLE
Scan.cpp: scan_displacement_references crashes if module region has unallocated gaps

### ISSUE THREAD

**Issue by ThirteenAG** [cursey/kananlib#5]
`return scan_displacement_references((uintptr_t)module, *module_size, ptr);`

Probably an odd case, but I noticed that scanner doesn't check for pointer validity, and this example has a gap of unallocated memory between `module` and `module + module_size`.

![image](https://github.com/cursey/kananlib/assets/4904157/97c4e362-fc38-4fd5-b013-6365187a9a7e)

![image](https://github.com/cursey/kananlib/assets/4904157/d425b977-27a2-4672-b2a2-c395e99ba7d0)

![image](https://github.com/cursey/kananlib/assets/4904157/1c2a03bf-91c8-455b-a61c-1f97e5e0e18a)

I'm attaching a minimal reproducible example, open Dll1.sln and run in debugger (it's pcsx2 emulator with injected dll).

```
const auto s = utility::scan_string(GetModuleHandleA(NULL), "    ================  EE COUNTER VSYNC START (frame: %d)  =======");
auto test = utility::scan_displacement_references(GetModuleHandleA(NULL), *s);
```

[test.7z.zip](https://github.com/user-attachments/files/15945152/test.7z.zip)
(spdlog is awkwardly removed in this, I would like to suggest making it available under a define)

**Comment by praydog** [comment]
Hmm, yeah that is a rare issue - never seen it myself in any Unreal game (hundreds) or RE Engine game, and a few others. A pre-emptive set of VirtualQuery calls to find valid regions in the scan area could work. Doing it during the AVX2 scan would defeat the purpose of how fast is it supposed to be.

**Comment by praydog** [comment]
A try-catch block would probably work too. Any exception handler really. Will have to see how that fares and if it even affects scan speed.

Just tested it:
Try-catch block around individual AVX2 block lowers scan speed from 11GB/s to 7GB/s
Try-catch block around entire unrolled loop lowers scan speed from 11GB/s to 10-10.5GB/s

**Comment by ThirteenAG** [comment]
Yeah, I was thinking there's no need to destroy performance during a loop, but maybe getting shorter size in get_module_size or something of the sort would do it as well. Exception handler ofc can be used too, I'm fine with whatever you decide is best.

**Comment by cursey** [comment]
A __try __except block around the scan shouldn't affect performance unless an exception is thrown.

**Comment by praydog** [comment]
Can you try latest commit and check if it fixes the issue you ran into?

I went with the __try/__except, it has a minimal performance hit. The hit does exist, though it's only around 500 MB/s off of an already 10.5-11GB/s scan on my machine, so not really anything of note.

I tried the VirtualQuery method initially, but VirtualQuery call takes 10ms for whatever reason (lowered speed down to 6GB/s), so that was completely unacceptable for the performance the scans are going for.

**Comment by ThirteenAG** [comment]
> Can you try latest commit and check if it fixes the issue you ran into?

Seems good, all string refs are found.
